import Link from 'next/link';

export const metadata = {
  title: 'Terms of Service — TaxAgent.ai',
  description: 'Terms and conditions for using TaxAgent.ai.',
};

const LAST_UPDATED = 'April 4, 2025';
const CONTACT_EMAIL = 'legal@taxagent.ai';

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-[var(--background)] px-6 pt-28 pb-16">
      <div className="mx-auto max-w-3xl">
      <p className="text-xs font-semibold uppercase tracking-[0.15em] text-emerald-400 mb-4">
        Legal
      </p>
      <p className="text-sm text-white/30 mb-2">Last updated: {LAST_UPDATED}</p>
      <h1 className="text-3xl sm:text-4xl font-bold text-white mb-4" style={{ letterSpacing: '-0.02em' }}>
        Terms of Service
      </h1>
      <p className="text-white/60 mb-10 leading-relaxed">
        Please read these Terms of Service (&quot;<strong>Terms</strong>&quot;) carefully
        before using TaxAgent.ai. By creating an account or using our service,
        you agree to be bound by these Terms.
      </p>

      <Section title="1. About TaxAgent.ai">
        <p>
          TaxAgent.ai provides an AI-assisted tax preparation guidance service for
          Canadian residents. We help you understand your tax situation and
          generate a personalised filing guide. We are <strong>not</strong> a
          registered tax preparer, chartered professional accountant (CPA), or
          legal advisor, and nothing on this platform constitutes professional
          tax or legal advice.
        </p>
        <p className="mt-3 font-medium text-white/70">
          TaxAgent.ai is not affiliated with, endorsed by, or connected to the
          Canada Revenue Agency (CRA).
        </p>
      </Section>

      <Section title="2. Eligibility">
        <p>
          You must be at least 18 years old and a resident of Canada to use this
          service. By using TaxAgent.ai, you represent that you meet these
          requirements.
        </p>
      </Section>

      <Section title="3. Your account">
        <ul className="space-y-2 list-disc list-inside text-white/60">
          <li>You are responsible for keeping your password confidential.</li>
          <li>
            You must provide accurate information. Filing a tax return based on
            incorrect information is your sole responsibility.
          </li>
          <li>
            You must notify us immediately of any unauthorised access to your
            account.
          </li>
        </ul>
      </Section>

      <Section title="4. Acceptable use">
        <p>You agree not to:</p>
        <ul className="mt-3 space-y-2 list-disc list-inside text-white/60">
          <li>Use the service for any unlawful purpose.</li>
          <li>
            Attempt to circumvent security measures or access other users&apos;
            accounts.
          </li>
          <li>Upload documents that do not belong to you.</li>
          <li>
            Use automated scripts to scrape or abuse the service.
          </li>
        </ul>
      </Section>

      <Section title="5. Disclaimer of warranties">
        <p>
          TaxAgent.ai is provided &quot;<strong>as is</strong>&quot; and &quot;
          <strong>as available</strong>&quot;. We make no warranty that:
        </p>
        <ul className="mt-3 space-y-2 list-disc list-inside text-white/60">
          <li>The service will be error-free or uninterrupted.</li>
          <li>
            Tax calculations or assessments generated by the AI will be
            accurate, complete, or suitable for filing.
          </li>
          <li>
            The service reflects the most current CRA rules and rates (we
            endeavour to keep it updated but make no guarantee).
          </li>
        </ul>
        <p className="mt-3">
          <strong>Always review your tax return carefully before submission.</strong>{' '}
          Consider consulting a licensed CPA for complex situations.
        </p>
      </Section>

      <Section title="6. Limitation of liability">
        <p>
          To the maximum extent permitted by applicable law, TaxAgent.ai and its
          operators shall not be liable for any indirect, incidental, special,
          consequential, or punitive damages arising from your use of the
          service, including any penalties, interest, or assessments levied by
          the CRA.
        </p>
        <p className="mt-3">
          Our total liability to you for any claim arising out of these Terms
          shall not exceed the amount you paid us in the 12 months preceding the
          claim.
        </p>
      </Section>

      <Section title="7. Intellectual property">
        <p>
          All content, software, and technology on TaxAgent.ai is owned by us
          and protected by Canadian intellectual property law. You may not copy,
          modify, or distribute any part of the service without our written
          permission.
        </p>
        <p className="mt-3">
          You retain ownership of all personal data and documents you upload.
          See our{' '}
          <Link href="/privacy" className="text-[var(--emerald)] hover:underline">
            Privacy Policy
          </Link>{' '}
          for details.
        </p>
      </Section>

      <Section title="8. Termination">
        <p>
          We may suspend or terminate your account if you violate these Terms.
          You may delete your account at any time. Upon termination, your right
          to use the service ends immediately, and we will delete your data in
          accordance with our Privacy Policy.
        </p>
      </Section>

      <Section title="9. Changes to these Terms">
        <p>
          We may update these Terms from time to time. Material changes will be
          communicated by email or prominent notice at least 14 days before they
          take effect. Continued use of the service after that date constitutes
          your acceptance of the new Terms.
        </p>
      </Section>

      <Section title="10. Governing law">
        <p>
          These Terms are governed by the laws of the Province of Ontario and
          the federal laws of Canada applicable therein, without regard to
          conflict of law principles.
        </p>
      </Section>

      <div className="mt-12 pt-8 border-t border-white/10 text-sm text-white/40">
        <p>
          Questions about these Terms? Email us at{' '}
          <a href={`mailto:${CONTACT_EMAIL}`} className="text-[var(--emerald)] hover:underline">
            {CONTACT_EMAIL}
          </a>
          .
        </p>
        <p className="mt-2">
          <Link href="/" className="text-[var(--emerald)] hover:underline">
            ← Back to home
          </Link>
        </p>
      </div>
      </div>
    </main>
  );
}

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  const eyebrow = title.replace(/^\d+\.\s*/, '').toUpperCase();
  return (
    <section className="mb-10">
      <p className="text-[10px] font-semibold uppercase tracking-[0.15em] text-emerald-400 mb-1">{eyebrow}</p>
      <h2 className="text-lg font-semibold text-white mb-3">{title}</h2>
      <div className="text-white/60 leading-relaxed">{children}</div>
    </section>
  );
}
