// AUTO-GENERATED — DO NOT HAND-EDIT
// Source: scripts/generate-slip-types.ts
// Regenerate: npm run gen:slip-types
//
// Maps CRA XSD internal field names → app-layer box keys used in types.ts.
// Used by /api/ocr to translate CRA XML field names to app types.

/** XSD field name → app box key for the T4 slip */
export const XSD_BOX_MAP_T4: Record<string, string> = {
  sin: 'box12',
  empt_prov_cd: 'box10',
  cpp_qpp_xmpt_cd: 'box28',
  ei_xmpt_cd: 'box29',
  empt_cd: 'box29',
  empr_dntl_ben_rpt_cd: 'box45',
  empt_incamt: 'box14',
  cpp_cntrb_amt: 'box16',
  cppe_cntrb_amt: 'box16A',
  qpp_cntrb_amt: 'box17',
  qppe_cntrb_amt: 'box17A',
  empe_eip_amt: 'box18',
  rpp_cntrb_amt: 'box20',
  itx_ddct_amt: 'box22',
  ei_insu_ern_amt: 'box24',
  cpp_qpp_ern_amt: 'box26',
  unn_dues_amt: 'box44',
  chrty_dons_amt: 'box46',
  padj_amt: 'box52',
  prov_pip_amt: 'box55',
  prov_insu_ern_amt: 'box56',
  hm_brd_lodg_amt: 'code30',
  spcl_wrk_site_amt: 'code32',
  prscb_zn_trvl_amt: 'code33',
  med_trvl_amt: 'code34',
  prsnl_vhcl_amt: 'code34',
  rsn_per_km_amt: 'code34',
  low_int_loan_amt: 'code36',
  empe_hm_loan_amt: 'code37',
  stok_opt_ben_amt: 'code38',
  sob_after_jun2024_amt: 'code38',
  sob_a00_feb_amt: 'code38',
  shr_opt_d_ben_amt: 'code39',
  sod_d_after_jun2024_amt: 'code39',
  sod_d_a00_feb_amt: 'code39',
  oth_tx_ben_amt: 'code40',
  shr_opt_d1_ben_amt: 'code41',
  sod_d1_after_jun2024_amt: 'code41',
  sod_d1_a00_feb_amt: 'code41',
  empt_cmsn_amt: 'code42',
  cfppa_amt: 'code43',
  dfr_sob_amt: 'code53',
  elg_rtir_amt: 'code66',
  nelg_rtir_amt: 'code67',
  indn_elg_rtir_amt: 'code68',
  indn_nelg_rtir_amt: 'code69',
  mun_ofcr_examt: 'code43',
  indn_empe_amt: 'code71',
  oc_incamt: 'code77',
  oc_dy_cnt: 'code78',
  fish_gro_ern_amt: 'code79',
  fish_net_ptnr_amt: 'code80',
  fish_shr_prsn_amt: 'code81',
  plcmt_emp_agcy_amt: 'code82',
  drvr_taxis_oth_amt: 'code83',
  cmpn_rpay_empr_amt: 'code84',
  brbr_hrdrssr_amt: 'code85',
  pub_trnst_pass_amt: 'code84',
  epaid_hlth_pln_amt: 'code85',
  pr_90_cntrbr_amt: 'code86',
  pr_90_ncntrbr_amt: 'code87',
  stok_opt_csh_out_eamt: 'code86',
  vlntr_emergencyworker_xmpt_amt: 'code87',
  indn_txmpt_sei_amt: 'code89',
  empt_inc_amt_covid_prd1: 'code57',
  empt_inc_amt_covid_prd2: 'code58',
  empt_inc_amt_covid_prd3: 'code59',
  empt_inc_amt_covid_prd4: 'code60',
  indn_xmpt_rpp_amt: 'code90',
  indn_xmpt_unn_amt: 'code91',
  lv_supp_top_up_amt: 'code77',
};

/** XSD field name → app box key for the T4A slip */
export const XSD_BOX_MAP_T4A: Record<string, string> = {
  pens_spran_amt: 'box016',
  lsp_amt: 'box018',
  self_empl_cmsn_amt: 'box020',
  itx_ddct_amt: 'box022',
  annty_amt: 'box024',
  fee_or_oth_srvc_amt: 'box048',
  elg_rtir_amt: 'box066',
  nelg_rtir_amt: 'box067',
  oth_incamt: 'box028',
  ptrng_aloc_amt: 'box150',
  rpp_past_srvc_amt: 'box032',
  padj_amt: 'box052',
  resp_aip_amt: 'box122',
  resp_educt_ast_amt: 'box130',
  chrty_dons_amt: 'box046',
  rsch_grnt_amt: 'box104',
  brsy_amt: 'box105',
  dth_ben_amt: 'box106',
  wag_ls_incamt: 'box107',
  lsp_rpp_nelg_amt: 'box114',
  nrgst_ppln_amt: 'box115',
  pr_71_acr_lsp_amt: 'box116',
  grp_trm_life_amt: 'box119',
  dsblt_ben_amt: 'box131',
  vtrn_ben_amt: 'box133',
  wag_ptct_pgm_amt: 'box138',
  tfsa_tax_amt: 'box145',
  indn_elg_rtir_amt: 'box068',
  indn_nelg_rtir_amt: 'box069',
  indn_oth_incamt: 'box070',
  indn_xmpt_pens_amt: 'box071',
  indn_xmpt_lsp_amt: 'box072',
  vtrn_ben_pens_splt_elg_amt: 'box133',
  alda_amt: 'box148',
  oas_lump_sum_pamt: 'box152',
  pst_dctrl_fshp_amt: 'box134',
  abe_tuit_ast_amt: 'box151',
  spp_sps_cntrb_ind: 'addInfoSpousalContrib',
  spp_sps_cntrbr_sin: 'addInfoSpousalSIN',
};

/** XSD field name → app box key for the T5 slip */
export const XSD_BOX_MAP_T5: Record<string, string> = {
  sin: 'box12',
  actl_elg_dvamt: 'box24',
  actl_dvnd_amt: 'box12',
  tx_elg_dvnd_pamt: 'box25',
  tx_dvnd_amt: 'box11',
  enhn_dvtc_amt: 'box26',
  dvnd_tx_cr_amt: 'box12B',
  cdn_int_amt: 'box13',
  oth_cdn_incamt: 'box14',
  fgn_incamt: 'box15',
  fgn_tx_pay_amt: 'box16',
  cdn_royl_amt: 'box17',
  cgain_dvnd_amt: 'box18',
  acr_annty_amt: 'box19',
  rsrc_alwnc_amt: 'box20',
  cgain_dvnd_1_amt: 'box18A',
  cgain_dvnd_2_amt: 'box18B',
  lk_nt_acr_intamt: 'box19B',
  cgain_dvnd_jan_to_jun_2024: 'box18C',
};

/** XSD field name → app box key for the T5008 slip */
export const XSD_BOX_MAP_T5008: Record<string, string> = {
  sin: 'recipientSIN',
  DISPN_DT: 'dispositionDate',
  fval_amt: 'box20',
  cost_bok_val_amt: 'box20',
  dispn_amt: 'box21',
  rcv_scty_tcd: 'receivedSecurityTypeCode',
  scty_rcv_cnt: 'box17',
  rcv_cusip_nbr: 'receivedCUSIP',
  id_scty_sttl_txt: 'box16',
  dsps_scty_tcd: 'disposedSecurityTypeCode',
  dsps_scty_cnt: 'box17',
  dsps_cusip_nbr: 'disposedCUSIP',
  id_scty_dsps_txt: 'box16',
  fgn_crcy_cd: 'foreignCurrencyCode',
  rcpnt_acct_nbr: 'box15',
  rcpnt_tcd: 'box22',
  dispn_trans_cnt: 'dispositionCount',
  sttl_amt: 'totalSettlementAmount',
};

/** XSD field name → app box key for the T3 slip */
export const XSD_BOX_MAP_T3: Record<string, string> = {
  cgamt: 'box21',
  actl_elg_dvamt: 'box22',
  actl_dvnd_amt: 'box32',
  oth_incamt: 'box26',
  elg_dedn_cgamt: 'box30',
  tx_elg_dvnd_pamt: 'box23',
  tx_dvnd_amt: 'box33',
  enhn_dvtc_amt: 'box24',
  dvnd_tx_cr_amt: 'box39',
  prd_2_cgamt: 'box21A',
  prd_3_cgamt: 'box21B',
  prd_2_elg_cgamt: 'box21C',
  prd_3_elg_cgamt: 'box21D',
  prd_2_insu_clamt: 'box21E',
  prd_3_insu_clamt: 'box21F',
  pens_lsp_amt: 'box31',
  fgn_bus_incamt: 'box34',
  fgn_nbus_incamt: 'box25',
  elg_pens_incamt: 'box31B',
  fgn_bus_tx_amt: 'box36',
  fgn_tx_amt: 'box37',
  dth_ben_amt: 'box41',
  insu_fnd_clamt: 'box42',
  XII_2_tx_cr_amt: 'box43',
  invs_cost_examt: 'box44',
  itc_amt: 'box45',
  oth_cr_amt: 'box46',
  amt_rslt_acb_amt: 'box26B',
  pens_trnsf_amt: 'box47',
  rtir_alwnc_amt: 'box48',
  chrty_dons_amt: 'box49',
  cg_disp_bef_jun_amt: 'box21G',
  cg_disp_after_jun_amt: 'box21H',
  cg_disp_qffp_bef_jun_amt: 'box21I',
  cg_disp_qffp_after_jun_amt: 'box21J',
  cg_disp_qsbcs_bef_jun_amt: 'box21K',
  cg_disp_qsbcs_after_jun_amt: 'box21L',
  ins_seg_bef_jun_amt: 'box21M',
  ins_seg_after_jun_amt: 'box21N',
};

/** XSD field name → app box key for the T2202 slip */
export const XSD_BOX_MAP_T2202: Record<string, string> = {
  TotalEligibleTuitionFeeAmount: 'boxA',
  TotalPartTimeStudentMonthCount: 'boxB',
  TotalFullTimeStudentMonthCount: 'boxC',
  EligibleTuitionFeeAmount: 'sessionBoxA',
  PartTimeStudentMonthCount: 'sessionBoxB',
  FullTimeStudentMonthCount: 'sessionBoxC',
  StartYearMonth: 'sessionStart',
  EndYearMonth: 'sessionEnd',
};

/** Unified lookup: XSD_BOX_MAP[slipType][xsdFieldName] → appBoxKey */
export const XSD_BOX_MAP: Record<string, Record<string, string>> = {
  T4: XSD_BOX_MAP_T4,
  T4A: XSD_BOX_MAP_T4A,
  T5: XSD_BOX_MAP_T5,
  T5008: XSD_BOX_MAP_T5008,
  T3: XSD_BOX_MAP_T3,
  T2202: XSD_BOX_MAP_T2202,
};